### ISSUE TITLE
BAL dataset(2) from supplementary figure S2 (I-O)

### ISSUE THREAD

**Issue by Deep1707** [saliba-lab/covid19-profibrotic-macrophages#2]
Hello,
Is it possible to get an R Seurat object or raw data for the dataset 2 BAL  in Supplementary figure 2(I-0)?

Thank you very much.

**Comment by OliverDietrich** [comment]
Hello Deep1707,

the raw (fastq) data is available on EGA.
I currently do not have access to the seurat.Rds or count matrices of the dataset 2 but I will notify you when that changes.

Best,

Oliver

**Comment by Deep1707** [comment]
Thanks. I would appreciate that.

> Hello Deep1707,
> 
> the raw (fastq) data is available on EGA. I currently do not have access to the seurat.Rds or count matrices of the dataset 2 but I will notify you when that changes.
> 
> Best,
> 
> Oliver

Thanks I would appreciate that. 

In the mean time, do you know who might have these data? Maybe Theis lab?

Thanks again.

Best,
Deepesh

**Comment by OliverDietrich** [comment]
Hello Deepesh,

I added the second dataset Rds files to the Nubes folder.

Best,

Oliver
